### ISSUE TITLE
h5netcdf version 1.0

### ISSUE THREAD

**Issue by kmuehlbauer** [h5netcdf/h5netcdf#113]
As recently brought up by @shoyer in https://github.com/h5netcdf/h5netcdf/pull/110#pullrequestreview-679253913, `h5netcdf` is approaching version 1.0 release. With the recent developments (eg. phony_dimensions, dimension scale handling and many fixes) the overall alignment with `netcdf4-python` was greatly improved.

There are still some incongruences and incompatibilities between `h5netcdf` and `netcdf4-python`. Some of them can and should  be addressed before version 1.0.

This issue should track all issues, pull requests and other missing things, that need to be tackled before version 1.0 is released. I'm starting with those I can contribute to. 

- [x] Issue #88 -> PR #104 + PR #112 (dimension scales)
- [x] Issue #98
- [x] Issue #52 (align with netcdf4 chunk-size heuristics) -> resolved by #127
- [x] Issue #36 (`isunlimited()`-method) #135 
- [x] Issue #23 (masking)  -> will be resolved by PR #103 and #125
- [x] PR #114 (issue & PR templates)
- [x] API documentation 
- [x] rename master -> main
- [x] Add Changelog.rst to source distribution #123
- [x] #116 
- [x] #129 
- [x] #134, #135
- [x] Issue #89, #161 --> PR #162, #163
- [ ] Issue #165, PR #166, [How does netcdf-c recognize netCDF4 format](https://github.com/Unidata/netcdf-c/discussions/2258)
- [x] #167
- [x] #168

**Comment by dionhaefner** [comment]
No love for #116? :cry:

**Comment by kmuehlbauer** [comment]
@dionhaefner I'll put it on the list.

**Comment by kmuehlbauer** [comment]
@shoyer I took the chance to release 0.14.0 with the recent changes, to have it into the wild before getting to 1.0. The API/documentation is the last point on this list for version 1.0. The due date is still end of March which should work.

**Comment by kmuehlbauer** [comment]
I've created a first version of documentation (currently available on my fork, https://kmuehlbauer.github.io/h5netcdf-docs/).

I'll have a PR ready the next days.

@shoyer It would be great if you could have a glance on the rendered docs. Also others are invited to have a look. Any comments appreciated.

**Comment by kmuehlbauer** [comment]
Things move along more or less smoothly. Version 0.15.0 is out now, adding the new documentation only. The documentation is now available via github pages https://h5netcdf.github.io/h5netcdf/.

Please note that `h5netcdf`-version `1.0` is due 31st of March 2022 in about two weeks from now. If there are any problems which should get fixed before the 1.0 release please open issues.

ping @drew-parsons regarding packaging at debian.

**Comment by kmuehlbauer** [comment]
There is one last blocker which need to be ruled out. 

In #165 we've identified a major problem with regard to writing standard conforming files. A possible solution was implemented and merged in #166. 

Additionally a discussion was initiated over at Unidata [How does netcdf-c recognize netCDF4 format](https://github.com/Unidata/netcdf-c/discussions/2258) to get to the bottom of this and come up with a future proof solution. If you have additional thoughts on that please join the discussion.

As a consequence we might have to postpone h5netcdf 1.0 until that discussion comes to a conclusion.

**Comment by shoyer** [comment]
The new documentation page looks great!

My main suggestion would be to switch around some content between the homepage and the "Overview" page. Right now the homepage talks mostly about the history of the project, but users are probably more interested in information from the "Overview", like the "Why h5netcdf" section. "History" could go in a less prominent location.

**Comment by shoyer** [comment]
With regards to identifying conforming netCDF files, I think your solution in #166 is about as well as you could hope to do. I don't think this should really be a blocker for h5netCDF 1.0. In my opinion, the NetCDF4 file format should always have required some explicit identification, but that was not the case originally.

**Comment by kmuehlbauer** [comment]
> With regards to identifying conforming netCDF files, I think your solution in #166 is about as well as you could hope to do. I don't think this should really be a blocker for h5netCDF 1.0. In my opinion, the NetCDF4 file format should always have required some explicit identification, but that was not the case originally.

Thanks, then I'd suggest we just move along with version 1.0 and adapt to a possible solution when https://github.com/Unidata/netcdf-c/discussions/2258 is resolved.

**Comment by kmuehlbauer** [comment]
We are finally approaching the release date (31st of March). There is the preparation PR #168 with some final changes. This PR will be merged later today to get a chance to see the docs build correctly etc.

Tomorrow would be the day for any last minute fixes. So if there is any immediate need to add changes/fixes please respond in time.

Final steps on Thursday:

- change `Development Version` to Version 1.0.0 (March 18th, 2022) in CHANGELOG.rst
- adapt last sentence in https://h5netcdf.org/#history to reflect release
- update CI sphinx-build to only deploy on release
- create release

**Comment by kmuehlbauer** [comment]
Sad this happens, but the PyPI-upload failed. I'll investigate.

**Comment by kmuehlbauer** [comment]
:tada: :rocket: **_We have just released h5netcdf version 1.0.0_** :rocket: :tada: 

- [h5netcdf 1.0.0 on PyPI](https://pypi.org/project/h5netcdf/)
- [h5netcdf docs on h5netcdf.org](https://h5netcdf.org/)

Many thanks to all who have contributed in one way or the other to make this happen, this is also your achievement. :1st_place_medal: 

:heart: Huge thanks from my side to Stephan for all his dedication and love for `h5netcdf`. BTW, @shoyer `h5netcdf` does not have some advertising channel, where we could announce this milestone? :mega: 

Looking forward to a healthy future for `h5netcdf`. :four_leaf_clover:
